// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "d7e2fea916659bbf271b4632f028fed5"
    },
    {
        "url": "icon-96.png",
        "revision": "f1bdf68dd999551760088eb79f5cbcba"
    },
    {
        "url": "icon-128.png",
        "revision": "1ec8980d1a4a78149a5ec7aac0a52a79"
    },
    {
        "url": "icon-144.png",
        "revision": "70839b0a9ce56b64a72ca87b9c29f139"
    },
    {
        "url": "icon-152.png",
        "revision": "24fd20976f6dc6d81b99bdecd571fced"
    },
    {
        "url": "icon-192.png",
        "revision": "286958b45be08bdc916b8e3126b2203d"
    },
    {
        "url": "icon-384.png",
        "revision": "d3d46f60ff5014f7d85d047e1c55329f"
    },
    {
        "url": "icon-512.png",
        "revision": "1a98134a086859d517de611e9e0579bc"
    },
    {
        "url": ".gitattributes",
        "revision": "05bdb783ee6514c8c072e47680af8ff7"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates new.py",
        "revision": "6f204d68894960c2efd7b6379cfbddab"
    },
    {
        "url": "favicon.ico",
        "revision": "eb8c914dbcdc153b613ffe483e9f45c4"
    },
    {
        "url": "index.html",
        "revision": "a8fa1821398e575dd068621aab4fd1f4"
    },
    {
        "url": "invoice.html",
        "revision": "6d7e6245c7959f0cbbfb95fb09cc8eb1"
    },
    {
        "url": "invoice2.html",
        "revision": "bb068b251424da5c8ae602540183fb4e"
    },
    {
        "url": "invoice_343_2024-07-15.png",
        "revision": "5e114feabd9ec4f5afec15e9a8f0f7f6"
    },
    {
        "url": "invoice_343_2025-07-15 (1).png",
        "revision": "96031c2a9be94da795be412053771b70"
    },
    {
        "url": "invoice_343_2025-07-15.png",
        "revision": "f2843a7b739770b4e1ce44999b2a985b"
    },
    {
        "url": "logo.jpg",
        "revision": "982b8101d5eff0244d33d0cfb47bd0a3"
    },
    {
        "url": "offline.html",
        "revision": "7656c61e25225c4fcc77cb000be6d527"
    },
    {
        "url": "signature.png",
        "revision": "987272800c52314669632b0ae42f4082"
    },
    {
        "url": "timesheet_Zubair_Ahmed_2025-08 (1).png",
        "revision": "7ff47c4f2fa5af5dce5498c566e5e502"
    },
    {
        "url": "timesheet_Zubair_Ahmed_2025-08 (2).png",
        "revision": "63505c91ab02d11edd307773ab885f17"
    },
    {
        "url": "timesheet_Zubair_Ahmed_2025-08.png",
        "revision": "f41f714d323c2f0a20ec91fac210ff3f"
    },
    {
        "url": "WhatsApp Image 2025-08-04 at 13.28.08_5b6f51b9.jpg",
        "revision": "5cc0a82f68584c767538d287381e2c2e"
    },
    {
        "url": "WhatsApp Image 2025-08-04 at 15.02.03_70ce4583.jpg",
        "revision": "c849d89397af362582d76b20c3468436"
    },
    {
        "url": "WhatsApp Image 2025-08-04 at 15.02.23_ece6d2a5.jpg",
        "revision": "386c79b1ed503d6c28d0bab774b88deb"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}