// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "d7e2fea916659bbf271b4632f028fed5"
    },
    {
        "url": "icon-96.png",
        "revision": "f1bdf68dd999551760088eb79f5cbcba"
    },
    {
        "url": "icon-128.png",
        "revision": "1ec8980d1a4a78149a5ec7aac0a52a79"
    },
    {
        "url": "icon-144.png",
        "revision": "70839b0a9ce56b64a72ca87b9c29f139"
    },
    {
        "url": "icon-152.png",
        "revision": "24fd20976f6dc6d81b99bdecd571fced"
    },
    {
        "url": "icon-192.png",
        "revision": "286958b45be08bdc916b8e3126b2203d"
    },
    {
        "url": "icon-384.png",
        "revision": "d3d46f60ff5014f7d85d047e1c55329f"
    },
    {
        "url": "icon-512.png",
        "revision": "1a98134a086859d517de611e9e0579bc"
    },
    {
        "url": ".gitattributes",
        "revision": "05bdb783ee6514c8c072e47680af8ff7"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates new.py",
        "revision": "6f204d68894960c2efd7b6379cfbddab"
    },
    {
        "url": "favicon.ico",
        "revision": "eb8c914dbcdc153b613ffe483e9f45c4"
    },
    {
        "url": "index.html",
        "revision": "9ac3c8add4d825e74c9845b9cef6f35e"
    },
    {
        "url": "invoice.html",
        "revision": "fa7f6c74e639e1aa61ca89f56fdf26cd"
    },
    {
        "url": "invoice2.html",
        "revision": "a94486b91b91174feab729850cba9c40"
    },
    {
        "url": "invoice_343_2024-07-15 (1).png",
        "revision": "a8cd083ca12361658f2a5c42d0b25376"
    },
    {
        "url": "invoice_343_2024-07-15.png",
        "revision": "5e114feabd9ec4f5afec15e9a8f0f7f6"
    },
    {
        "url": "invoice_343_2025-07-15 (1).png",
        "revision": "96031c2a9be94da795be412053771b70"
    },
    {
        "url": "invoice_343_2025-07-15.png",
        "revision": "f2843a7b739770b4e1ce44999b2a985b"
    },
    {
        "url": "log (1).jpeg",
        "revision": "489741c20cceecdc0110d297a293ea65"
    },
    {
        "url": "log (1).png",
        "revision": "f693ce8537846de882ebd13f5b535523"
    },
    {
        "url": "log (2) bg.jpg",
        "revision": "0f8241393557842ee731af21f232ce04"
    },
    {
        "url": "log (2).jpeg",
        "revision": "648b9857df83827d9e8341aeefde170b"
    },
    {
        "url": "log (2).png",
        "revision": "d6dbbcb03f92c79beb64866dfeda5f8a"
    },
    {
        "url": "log (3).png",
        "revision": "ab51086d9aba027fa090c841a8545934"
    },
    {
        "url": "logo (1).jpeg",
        "revision": "1f5b42adfba61aade5ae72b57b9d0c34"
    },
    {
        "url": "logo (1).png",
        "revision": "b3f5922a7b4845063f82f7416f265894"
    },
    {
        "url": "logo (10).jpeg",
        "revision": "70187bc440fbdd372972c423ec0bbce0"
    },
    {
        "url": "logo (11).jpeg",
        "revision": "faf3b54e9682bc0c9a23d1eff9645a29"
    },
    {
        "url": "logo (2).jpeg",
        "revision": "acfc7bb7b7a4c331012d096bbe25bf8b"
    },
    {
        "url": "logo (2).png",
        "revision": "8400bd91ca195d92948c9020e8497054"
    },
    {
        "url": "logo (3).jpeg",
        "revision": "e82e10cc59b3093936a01fbeccb4d490"
    },
    {
        "url": "logo (3).png",
        "revision": "05da493e426a440fc8acc0141fdc991b"
    },
    {
        "url": "logo (4).jpeg",
        "revision": "04177d2d9b37232a3f07a9cffad4de9e"
    },
    {
        "url": "logo (4).png",
        "revision": "a416b55ade67a749a8b80738492d8c7b"
    },
    {
        "url": "logo (5).jpeg",
        "revision": "52879bb1f54a7d80b5579ecc1a9eec7d"
    },
    {
        "url": "logo (6).jpeg",
        "revision": "57e0d12de7d08dc553e592c51c56807f"
    },
    {
        "url": "logo (7).jpeg",
        "revision": "47db837454b9bac22bf8b8027d30f947"
    },
    {
        "url": "logo (8).jpeg",
        "revision": "10b6f1c8d9f8643f8e7fa792afcde8c1"
    },
    {
        "url": "logo (9).jpeg",
        "revision": "138a8c160230f77e3a45fe29a595e858"
    },
    {
        "url": "logo.jpg",
        "revision": "982b8101d5eff0244d33d0cfb47bd0a3"
    },
    {
        "url": "manifest.json",
        "revision": "2819f97ba2a0b318c2d9c5e6e5ab222b"
    },
    {
        "url": "offline.html",
        "revision": "ae51d343db40057d79a35f860555d2b1"
    },
    {
        "url": "signature.png",
        "revision": "987272800c52314669632b0ae42f4082"
    },
    {
        "url": "sw.js",
        "revision": "84bd65d466eb6d662b20cca55c5e3ee7"
    },
    {
        "url": "timesheet_Zubair_Ahmed_2025-08 (1).png",
        "revision": "7ff47c4f2fa5af5dce5498c566e5e502"
    },
    {
        "url": "timesheet_Zubair_Ahmed_2025-08 (2).png",
        "revision": "63505c91ab02d11edd307773ab885f17"
    },
    {
        "url": "timesheet_Zubair_Ahmed_2025-08.png",
        "revision": "69e259b17bca01c4637d6a39c0286517"
    },
    {
        "url": "WhatsApp Image 2025-08-04 at 13.28.08_5b6f51b9.jpg",
        "revision": "5cc0a82f68584c767538d287381e2c2e"
    },
    {
        "url": "WhatsApp Image 2025-08-04 at 15.02.03_70ce4583.jpg",
        "revision": "c849d89397af362582d76b20c3468436"
    },
    {
        "url": "WhatsApp Image 2025-08-04 at 15.02.23_ece6d2a5.jpg",
        "revision": "386c79b1ed503d6c28d0bab774b88deb"
    },
    {
        "url": "WhatsApp Image 2025-08-13 at 14.28.46_84c62915.jpg",
        "revision": "ee8c55dc1620be09de47b51cf051126a"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}